In [37]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [38]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast',
       'Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool',
     'Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes',
     'No','Yes','Yes','Yes','Yes','Yes','No']

In [39]:
_label=preprocessing.LabelEncoder()
weather_encoded=_label.fit_transform(weather)
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [40]:
_label=preprocessing.LabelEncoder()
temp_encoded=_label.fit_transform(temp)
print(temp_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [41]:
features=list(zip(weather_encoded,temp_encoded))
features

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [42]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
play_encoded = _label.fit_transform(play)
print(play_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [44]:
model=KNeighborsClassifier(n_neighbors=3)
model.fit(features,play_encoded)

KNeighborsClassifier(n_neighbors=3)

In [45]:
predicted=model.predict([[0,2]]) #sınıf belirleme yes no mu?
print(predicted)

[1]


In [80]:
from sklearn import datasets
wine=datasets.load_wine()

In [81]:
print(wine.feature_names)
print(wine.target_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
['class_0' 'class_1' 'class_2']


In [82]:
print(wine.data[0:5])

[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [83]:
print(wine.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [84]:
print(wine.data.shape)
print(wine.target.shape)

(178, 13)
(178,)


In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.3)

In [90]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=25,metric="manhattan")
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print(y_pred)
print(y_test)

from sklearn import metrics
print("Accuracy= ",metrics.accuracy_score(y_test,y_pred))

[0 1 2 2 0 2 0 2 2 2 1 0 2 1 0 2 1 2 2 0 1 1 2 0 1 2 0 2 1 0 2 1 0 1 1 0 0
 2 0 2 2 1 2 1 0 1 1 0 0 1 0 1 1 0]
[2 1 1 2 0 2 0 0 2 2 2 1 1 1 0 0 1 1 1 0 1 1 2 0 1 2 0 2 1 0 2 1 0 1 1 1 0
 1 0 2 2 1 2 1 1 1 1 0 0 1 0 2 1 0]
Accuracy=  0.7592592592592593
